---
title: "UMBS LTREB Soils Table Cleaning"
author: "Alexandria Pawlik"
output: html_notebook
---

Required packages and paths
```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
library(xlsx)
library(tibble)
library(dataMaid)
options(stringsAsFactors = FALSE)

# set these paths for your machine's specifics
soils_path <- "../raw/soils_2014_from_Mfield.csv"
output_path <- "../output/soils.csv"

# output site IDs
plots_path <- "../plots/soils_plots.csv"
```



Read in data
*Input is from exported first sheet of ../raw/excel/UMBS_LTREB_soils_for_IMS.xlsx, downloaded from private Mfield dataset posted by Luke*
```{r}
soils <- read_csv(soils_path, col_types = "ccccidcdddddcddccdddfiiidddddddddddi")
glimpse(soils)

# make sure missing values are all filled in
lapply(soils, identifyMissing)
```

Change column names to fit EDI standards
```{r}
soils <- soils %>% 
  rename(Plot_ID = Plot) %>% 
  rename(Profile_ID = `Profile ID`) %>% 
  rename(Targeted_Sampling_Increment = `Targeted sampling increment`) %>% 
  rename(Actual_Sampling_Increment = `Actual sampling increment`) %>% 
  rename(Sampling_Increment_Thickness = `Sampling increment thickness (cm)`) %>% 
  rename(Sample_Volume = `Sample volume (cm^3)`) %>% 
  rename(Archived_Sample_ID = `Archived sample ID`) %>% 
  rename(Fine_Earth_Dry_Mass = `Fine earth 60 degrees dry mass (g)`) %>% 
  rename(Root_Dry_Mass = `Root  60 degrees  dry mass (g)`) %>% 
  rename(Wood_Dry_Mass = `Wood greater than 2mm 60 degrees dry mass (g)`) %>% 
  rename(Stone_Dry_Mass = `Stone Air Dry mass (g)`) %>% 
  rename(Stone_Volume = `Stone volume (cm3)`) %>% 
  rename(Sieving_Comments = `Sieving comments`) %>% 
  rename(Fine_Earth_Mass_Density = `Fine earth mass density (Mg ha-1)`) %>% 
  rename(Fine_Earth_Bulk_Density = `Fine earth bulk density (g cm-3)`) %>% 
  rename(Bulk_Density_Code = `Bulk density code`) %>% 
  rename(PH = pH) %>% 
  rename(Percent_Loss_On_Ignition = `Loss on ignition (%)`) %>% 
  rename(Percent_C_Concentration = `Total C concentration (%)`) %>% 
  rename(C_Concentration_Code = `C concentration code`) %>% 
  rename(Ca_Concentration = `Ca (mg kg-1)`) %>% 
  rename(K_Concentration = `K (mg kg-1)`) %>% 
  rename(Mg_Concentration = `Mg (mg kg-1)`) %>% 
  rename(P_Concentration = `P (mg kg-1)`) %>% 
  rename(Al_Concentration = `Al (mg kg-1)`) %>% 
  rename(Cu_Concentration = `Cu (mg kg-1)`) %>% 
  rename(Fe_Concentration = `Fe (mg kg-1)`) %>% 
  rename(Mn_Concentration = `Mn (mg kg-1)`) %>% 
  rename(Na_Concentration = `Na (mg kg-1)`) %>% 
  rename(S_Concentration = `S (mg kg-1)`) %>% 
  rename(Zn_Concentration = `Zn (mg kg-1)`) %>% 
  rename(Acidity = `acidity (meq 100 g-1)`) %>% 
  rename(ECEC = `ECEC (meq 100g-1)`) %>% 
  rename(Root_C_Stock = `Root C stock (Mg C ha-1)`) %>% 
  rename(Soil_C_Stock = `Soil C stock (Mg C ha-1)`)

# move unique ID column to be first
soils <- soils %>% relocate(Archived_Sample_ID, .before = 1)

glimpse(soils)
```

Fix categorical values
```{r}
soils$Texture[soils$Texture == "s. clay loam"] <- "sandy clay loam"
soils$Sieving_Comments <- toupper(soils$Sieving_Comments)
soils$Texture <- toupper(soils$Texture)
soils$C_Concentration_Code <- toupper(soils$C_Concentration_Code)

# fix missing values for masses (NA is 0 mass)
soils$Stone_Dry_Mass[soils$Stone_Volume == 0] <- 0
soils$Root_Dry_Mass[is.na(soils$Root_Dry_Mass)] <- 0
soils$Wood_Dry_Mass[is.na(soils$Wood_Dry_Mass)] <- 0
soils$Stone_Dry_Mass[is.na(soils$Stone_Dry_Mass)] <- 0
soils$Stone_Volume[soils$Stone_Dry_Mass == 0] <- 0 # zero mass is zero volume, fixes NAs
```

Fix precision based on lab procedure
```{r}
soils$Fine_Earth_Dry_Mass <- round(soils$Fine_Earth_Dry_Mass, digits = 2)
soils$Root_Dry_Mass <- round(soils$Root_Dry_Mass, digits = 2)
soils$Wood_Dry_Mass <- round(soils$Wood_Dry_Mass, digits = 2)
soils$Stone_Dry_Mass <- round(soils$Stone_Dry_Mass, digits = 2)
soils$Stone_Volume <- round(soils$Stone_Volume, digits = 1)
```

Fix plot IDs
```{r}
soils <- soils %>% 
  mutate(Profile_ID = str_remove(Profile_ID, Plot_ID)) %>% 
  mutate(Profile_ID = str_remove(Profile_ID, "\\.")) %>% 
  mutate(C_Concentration_Code = str_remove(C_Concentration_Code, "\\."))
soils$Plot_ID <- str_replace(soils$Plot_ID, "#", "")
soils$Plot_ID <- str_replace(soils$Plot_ID, "CP", "IP")
soils$Plot_ID[soils$Plot_ID == "BF1"] <- "BP541"  # given by Alina
soils$Plot_ID[soils$Plot_ID == "BF2"] <- "BP542" # given by Alina

# store plot names
plots <- unique(soils$Plot_ID) %>% sort(.)
```

Output CSV
```{r}
# write.csv(soils, file = output_path, row.names = FALSE)
soils <- soils %>% arrange(Plot_ID, Profile_ID)
glimpse(soils)
write.csv(soils, file = output_path, eol = "\r\n", row.names = FALSE)
# write_csv(soils, output_path)

# output plot list
write.csv(plots, file = plots_path, row.names = FALSE)
```






