---
title: "UMBS LTREB Coarse Woody Debris Table Cleaning"
author: "Alexandria Pawlik and Alina Drebin"
output: html_notebook
---

Using R version 4.0.1 (2020-06-06)

Required packages and paths
```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
library(xlsx)
library(tibble)
library(dataMaid)
options(stringsAsFactors = FALSE)

# set these paths for your machine's specifics
cwd_path_2014 <- "../raw/CWD_2014_raw.csv"
cwd_path_2019 <- "../raw/CWD_2020_raw.csv"
output_path <- "../output/cwd.csv"
plots_path <- "../plots/cwd_plots.csv"  # output site IDs
```

Read in data
```{r}
# 2014
cwd_14 <- read_csv(cwd_path_2014, col_types = "ccc-icddddid---ddd")
# remove row with only NA
cwd_14 <- cwd_14 %>% 
  filter_all(any_vars(!is.na(.)))

# 2019
cwd_19 <- read_csv(cwd_path_2019, col_types = "ccicddddid-d-dd-")
# remove row with only NA
cwd_19 <- cwd_19 %>% 
  filter_all(any_vars(!is.na(.)))

glimpse(cwd_14)
glimpse(cwd_19)
```

Fix column names to conform to EDI standards
```{r}
cwd_14 <- cwd_14 %>% 
  rename(Stand_Name = `Stand name`) %>% 
  rename(Date = `Date Sampled`) %>% 
  rename(Plot_ID = `Plot ID`) %>% 
  rename(CWD_Subplot_ID = `CWD subplot ID`) %>% 
  rename(Species = `Species code (if possible)`) %>% 
  rename(Length = `Length (m)`) %>% 
  rename(Endpoint_1_Diameter = `Endpoint 1 diameter (cm)`) %>% 
  rename(Midpoint_Diameter = `Midpoint diameter (cm)`) %>% 
  rename(Endpoint_2_Diameter = `Endpoint 2 diameter (cm)`) %>% 
  rename(Decay_Class_Whole_Piece = `Decay class of whole piece`) %>% 
  rename(Average_Diameter = `Avg. Diameter (cm)`) %>% 
  rename(Estimated_Volume_Tapered = `Est. Tapered Volume (cm^3)`) %>% 
  rename(Estimated_Biomass_Tapered = `Estimated Biomass (taper) (g)`)

# incorrect unit in 2014 Volume - forgot to convert length to cm before multiplying for volume?
cwd_14 <- cwd_14 %>% 
  mutate(Estimated_Volume_Tapered = Estimated_Volume_Tapered * 100)
# subsequent error in 2014 Biomass - input volume was too small
cwd_14 <- cwd_14 %>% 
  mutate(Estimated_Biomass_Tapered = Estimated_Biomass_Tapered * 100)

cwd_19 <- cwd_19 %>% 
  rename(Date = `Date sampled`) %>% 
  rename(Plot_ID = `Plot`) %>% 
  rename(CWD_Subplot_ID = `CWD subplot ID`) %>% 
  rename(Species = `Species code (if possible)`) %>% 
  rename(Length = `Length (m)`) %>% 
  rename(Endpoint_1_Diameter = `Endpoint 1 diameter (cm)`) %>% 
  rename(Midpoint_Diameter = `Midpoint diameter (cm)`) %>% 
  rename(Endpoint_2_Diameter = `Endpoint 2 diameter (cm)`) %>% 
  rename(Decay_Class_Whole_Piece = `Decay class of whole piece`) %>% 
  rename(Average_Diameter = `Avg diameter (cm)`) %>% 
  rename(Estimated_Volume_Tapered = `Volume (cm3)`) %>% 
  rename(Estimated_Biomass_Tapered = `Mass (kg)`) %>% 
  rename(Density = `Density (g cm-3)`) %>% 
  mutate(Estimated_Biomass_Tapered = Estimated_Biomass_Tapered * 1000) %>% # convert to g
  mutate(Stand_Name = NA, .before = 1)

glimpse(cwd_14)
glimpse(cwd_19)
```

Create status column to represent if stump or not and take "stump" out of species code column
```{r}
cwd_14 <- cwd_14 %>% 
  mutate(Status = ifelse(str_sub(Species, 1, 8)=="Stump - ", "Stump", NA))

cwd_14 <- cwd_14 %>% 
  mutate(Species = ifelse(str_sub(Species, 1, 8)=="Stump - ", str_sub(Species, 9, -1), Species))

cwd_14$Status[cwd_14$Species == "Stump Piece - PIST"] <- "Stump"
cwd_14$Species[cwd_14$Species == "Stump Piece - PIST"] <- "PIST"


cwd_19 <- cwd_19 %>% 
  mutate(Status = ifelse(str_sub(Species, 1, 5)=="Stump", "Stump", NA))

cwd_19 <- cwd_19 %>% 
  mutate(Species = ifelse(str_sub(Species, 1, 7)=="Stump- ", str_sub(Species, 8, -1), Species))
```

Merge and fix missing values
```{r}
# convert date to standard format
cwd_14$Date <- mdy(cwd_14$Date)
cwd_19$Date <- mdy(cwd_19$Date)

# merge
cwd_14 <- cwd_14 %>% select(1, 3, 4, 2, 5, 15, 6, 7:14)
cwd_19 <- cwd_19 %>% select(1, 2, 4, 3, 5, 15, 6, 7:11, 13, 12, 14)
cwd <- rbind(cwd_14, cwd_19)

# missing values
cwd$Species[str_sub(cwd$Species, 1, 1) == "?"] <- NA
cwd$Species[cwd$Species == "Unknown"] <- NA

# change all 0 biomasses to NA when volume isn't 0
cwd$Estimated_Biomass_Tapered[cwd$Estimated_Biomass_Tapered == 0] <- NA

# fix species values
identifyLoners(cwd$Species)
```

Fix plot names
```{r}
cwd$Plot_ID[cwd$Plot_ID == "BS42A&BS42C"] <- NA
cwd$Plot_ID[cwd$Plot_ID == "BF1"] <- "BP54#1"  # given by Alina
cwd$Plot_ID[cwd$Plot_ID == "BF2"] <- "BP54#2" # given by Alina
cwd$Plot_ID[cwd$Plot_ID == "Wells"] <- "WELLS"
cwd$Plot_ID[cwd$Plot_ID == "1"] <- "DNR1"
cwd$Plot_ID[cwd$Plot_ID == "2"] <- "DNR2"
cwd$Plot_ID[cwd$Plot_ID == "3"] <- "DNR3"
cwd$Plot_ID <- str_replace(cwd$Plot_ID, "CP", "IP")
cwd$Plot_ID <- str_replace(cwd$Plot_ID, "PSA1972", "PSA")
cwd$Plot_ID <- str_replace(cwd$Plot_ID, "PSA72", "PSA")
cwd$Plot_ID <- str_replace(cwd$Plot_ID, "DNR87", "DNR")
cwd$Plot_ID <- str_replace(cwd$Plot_ID, "#", "")

cwd$Stand_Name <- str_replace(cwd$Stand_Name, "CP", "IP")

# store plot names
plots <- unique(cwd$Plot_ID) %>% sort(.)
plots
```

Generate stand name values for 2019
```{r}
# create a dictionary of stand names
stand_names <- cwd %>% 
  distinct(Stand_Name, Plot_ID) %>% 
  filter(!is.na(Stand_Name))

# re-create the stand-names column
cwd <- cwd %>% select(-Stand_Name)
cwd <- merge(cwd, stand_names, by="Plot_ID", x.all = TRUE)
cwd <- cwd %>% relocate(Stand_Name, .before = 1)

# check for duplicates
test <- cwd %>% select(-Stand_Name) %>% 
  distinct(.)

# stand name seems redundant
cwd <- cwd %>%
  select(-Stand_Name)
```


Write csv file
```{r}
write.csv(cwd, file = output_path, eol = "\r\n", row.names = FALSE)

# output plot list
# write.csv(plots, file = plots_path, eol = "\r\n", row.names = FALSE)

glimpse(cwd)
```

Plots
```{r}
library(ggplot2)
# plot diameter vs estimated volume
cwd <- cwd %>% mutate(Year = year(Date))
ggplot(cwd, aes(x=Average_Diameter, y=Estimated_Biomass_Tapered, color=Year)) +
    geom_point(size=2)

ggplot(cwd_14, aes(x=Average_Diameter, y=Estimated_Volume_Tapered, color=Status)) +
    geom_point(size=2)
ggplot(cwd_19, aes(x=Average_Diameter, y=Estimated_Volume_Tapered, color=Status)) +
    geom_point(size=2)
```

Check computation
```{r}
# Average diameter OK
cwd <- cwd %>% 
  mutate(T_Average_Diameter = (Endpoint_1_Diameter + Endpoint_2_Diameter + Midpoint_Diameter) * (1/3), .after="Average_Diameter")
cwd[cwd$Average_Diameter != round(cwd$T_Average_Diameter, digits = 1), ]

# Tapered volume
cwd <- cwd %>% 
  mutate(T_Estimated_Volume_Tapered = (Length * 100) * (T_Average_Diameter / 2)^2 * pi, .after="Estimated_Volume_Tapered")
cwd[cwd$T_Estimated_Volume_Tapered != cwd$Estimated_Volume_Tapered, ]

# Tapered biomass
cwd <- cwd %>% 
  mutate(T_Estimated_Biomass_Tapered = T_Estimated_Volume_Tapered * Density, .after="Estimated_Biomass_Tapered")
cwd[cwd$T_Estimated_Biomass_Tapered != cwd$Estimated_Biomass_Tapered, ]


# which cols have NAs
unlist(lapply(cwd, function(x) any(is.na(x))))
```



