---
title: "UMBS LTREB 2019 Above Ground Biomass Table Cleaning"
author: "Alexandria Pawlik"
output: html_notebook
---

Usign R version 4.0.1 (2020-06-06)
**Cleaning for AGB data before 2019 was completed by Alina Drebin for package edi.243.2, however no script exists for that cleaning process**

Required packages and paths
```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
library(xlsx)
library(tibble)
library(dataMaid)
options(stringsAsFactors = FALSE)

# set these paths for your machine's specifics
clean_2014_path <- "../raw/AGB_2014_clean.csv"
raw_2019_path <- "../raw/AGB_2019_raw.csv"
output_path <- "../output/agb.csv"
# output_history_path <- "../output/tree_history.csv"  NEVER FINISHED

# output site IDs
plots_path <- "../plots/agb_plots.csv"
```


Pull in 2019 data and cleaned 2014 data
```{r}
clean_14 <- read_csv(clean_2014_path, col_types = "icciDiiccccdcdddddcc")
raw_19 <- read_csv(raw_2019_path, col_types = "ccddcccddcccccccc")

# remove unnecessary columns and rows
clean_14 <- clean_14 %>%
  select(-Sort, -Common_name)

raw_19 <- raw_19 %>% 
  select(-X12, -X13, -X14, -X15, -X16, -X17) %>% 
  filter_all(any_vars(!is.na(.)))
```

Fix all column names
```{r}
# rename
clean_14 <- clean_14 %>% 
  rename(Species = Species_code) %>% 
  rename(Plot_ID = Plot) %>% 
  rename(LTREB_Tag = LTREB_tag) %>% 
  rename(Old_Tag = Old_tag) %>% 
  rename(Outside_Historic_Plot = Outside_historic_plot) %>% 
  rename(Measure_Year = Measure_year) %>% 
  rename(Origin_Year = Origin_year) %>% 
  rename(Years_Standing = Stand_year) %>% 
  rename(DBH = DBH_cm) %>% 
  rename(As_Class = As_class) %>% 
  rename(AGB = AGB_kg) 

raw_19 <- raw_19 %>% 
  rename(Plot_ID = Plot) %>% 
  rename(Distance = `Dist (m)`) %>% 
  rename(Azimuth = `Azi (°)`) %>% 
  rename(Status = `Live or Dead?`) %>% 
  rename(LTREB_Tag = `Tag #`) %>% 
  rename(DBH = `DBH (cm)`) %>% 
  rename(AGB = `AGB (kg)`) %>% 
  rename(Estimated_Height = `Estimated height (m)`)

# merge height columns in 2014
clean_14 %>% filter(!is.na(Height_stem) & !is.na(Height_dead)) # never have both values

clean_14 <- clean_14 %>%
  mutate(Estimated_Height = ifelse(!is.na(Height_stem), Height_stem, Height_dead)) %>% 
  select(-Height_stem, -Height_dead)

# reorder columns to put keys first
clean_14 <- clean_14 %>% 
  relocate(LTREB_Tag, .before = 1) %>% 
  relocate(Old_Tag, .after = LTREB_Tag) %>% 
  relocate(Species, .after = Old_Tag)

raw_19 <- raw_19 %>% 
  relocate(LTREB_Tag, .before = 1) %>% 
  relocate(Species, .after = LTREB_Tag) %>% 
  relocate(Plot_ID, .after = Species)
```


Fix up 2014 data first
```{r}
# remove tag NA values
clean_14$LTREB_Tag[clean_14$LTREB_Tag == "?"] <- NA
clean_14$Old_Tag[clean_14$Old_Tag == "?"] <- NA
clean_14$Notes[clean_14$Old_Tag == "unreadable"] <- "old tag unreadable"
clean_14$Old_Tag[clean_14$Old_Tag == "unreadable"] <- NA
clean_14$LTREB_Tag[clean_14$LTREB_Tag == "None"] <- NA
clean_14$Old_Tag[clean_14$Old_Tag == "None"] <- NA
clean_14$Notes[clean_14$Old_Tag == "FALLEN, ALIVE"] <- "FALLEN, ALIVE"
clean_14$Old_Tag[clean_14$Old_Tag == "FALLEN, ALIVE"] <- NA
clean_14$Notes[clean_14$Old_Tag == "eaten"] <- "tag eaten"
clean_14$Old_Tag[clean_14$Old_Tag == "eaten"] <- NA

# fix missing species
clean_14$Species[clean_14$Species == "UNKNOWN"] <- NA

# fix boolean columns
clean_14$Outside_Historic_Plot[is.na(clean_14$Outside_Historic_Plot)] <- "N"
clean_14$As_Class[!is.na(clean_14$As_Class)] <- "Y"
clean_14$As_Class[is.na(clean_14$As_Class)] <- "N"
```

Clean up 2019 data
```{r}
# convert 2019 dates to proper format
raw_19$Date <- as.Date(raw_19$Date, format = "%m/%d/%y")

# convert tree heights to proper format, move strings to Notes
unique(raw_19$Estimated_Height)

raw_19$Notes[is.na(raw_19$Notes) & 
               !is.na(raw_19$Estimated_Height) & 
               raw_19$Estimated_Height == "intact"] <- "intact" 

raw_19$Notes[is.na(raw_19$Notes) & 
               !is.na(raw_19$Estimated_Height) & 
               raw_19$Estimated_Height == "full tree"] <- "full tree" 

raw_19$Estimated_Height[raw_19$Estimated_Height == "intact"] <- NA
raw_19$Estimated_Height[raw_19$Estimated_Height == "full tree"] <- NA

# all caps
raw_19$Notes <- toupper(raw_19$Notes)

# move changed tag numbers to new column
raw_19 <- raw_19 %>%
  mutate(LTREB_Tag_2014 = ifelse(!is.na(Notes) & str_sub(Notes, 1, 16)=="FORMERLY TAGGED ", str_sub(Notes, 17, -1), LTREB_Tag), .after = LTREB_Tag) %>%
  mutate(LTREB_Tag_2014 = ifelse(!is.na(Notes) & str_sub(Notes, 1, 16)=="NEW TREE", NA, LTREB_Tag_2014))
```

Extract tree history to second table
```{r}
# distinguish between LTREB 14 and 19 tags
clean_14 <- clean_14 %>% 
  rename(LTREB_Tag_2014 = LTREB_Tag)

raw_19 <- raw_19 %>% 
  rename(LTREB_Tag_2019 = LTREB_Tag)

# tree_history table 

# tree_history <- 
#   full_join(clean_14, raw_19, by = c("LTREB_Tag_2014", "Species", "Plot_ID"), na_matches = "never") %>% 
#   select(LTREB_Tag_2019, LTREB_Tag_2014, Old_Tag, Species, Plot_ID, Outside_Historic_Plot, Origin_Year) %>% 
#   arrange(LTREB_Tag_2019, LTREB_Tag_2014, Old_Tag) %>% 
#   filter_all(any_vars(!is.na(.))) 

tree_history <- clean_14 %>% 
  select(LTREB_Tag_2014, Old_Tag, Species, Plot_ID, Outside_Historic_Plot, Origin_Year, Years_Standing) %>%
  filter_all(any_vars(!is.na(.)))
# NOT READY FOR EXPORT
```

Merge 2014 and 2019 data
```{r}
# match up columns
agb14 <- clean_14 %>% 
  relocate(Distance, .after = "Date") %>% 
  relocate(Azimuth, .after = "Distance") %>% 
  relocate(Status, .after = "Azimuth") %>% 
  relocate(Notes, .after = "Estimated_Height") %>% 
  mutate(LTREB_Tag_2019 = NA, .before = 1)

agb19 <- raw_19 %>% 
  mutate(As_Class = "N", .after = "DBH") %>% 
  mutate(Measure_Year = "2019", .before = "Date")

# get some tree history data from 2014 dataset
agb19_lookup <- 
  left_join(agb19, tree_history, by = c("LTREB_Tag_2014", "Species", "Plot_ID"), na_matches = "never") %>% 
  arrange(LTREB_Tag_2019, LTREB_Tag_2014, Old_Tag)

# fix 3 duplicate rows
agb19_lookup %>% 
  group_by(LTREB_Tag_2019, LTREB_Tag_2014, Species, Plot_ID, Measure_Year, Date, Distance, Azimuth, Status, DBH, As_Class, AGB, Estimated_Height, Notes) %>% 
  filter(n()>1)

agb19_lookup <- agb19_lookup[-c(2687),]
agb19_lookup %>% filter(LTREB_Tag_2019 == "3760")

agb19_lookup <- agb19_lookup[-c(1303),]
agb19_lookup %>% filter(LTREB_Tag_2019 == "2293")

agb19_lookup <- agb19_lookup[-c(2611),]
agb19_lookup %>% filter(LTREB_Tag_2019 == "3683")

# calculate years standing for 2019
agb19 <-  agb19_lookup %>% 
  mutate(Years_Standing = as.numeric(Years_Standing) + 5)

# rearrange new columns
agb19 <- agb19 %>% 
  relocate(Old_Tag, .after = "LTREB_Tag_2014") %>% 
  relocate(Outside_Historic_Plot, .after = "Plot_ID") %>% 
  relocate(Origin_Year, .after = "Status") %>% 
  relocate(Years_Standing, .after = "Origin_Year")

names(agb14)
names(agb19)

# combine
agb <- rbind(agb14, agb19) %>% 
  mutate(Estimated_Height = as.numeric(Estimated_Height)) %>% 
  mutate(DBH = as.numeric(DBH))
glimpse(agb)

# make sure missing values are all filled in
lapply(agb, identifyMissing)

# get rid of tree data without species
agb <- agb %>% 
  filter(!is.na(Species))
```

Fix plot names
```{r}
agb$Plot_ID[agb$Plot_ID == "BS42A&BS42C"] <- "BS42"
agb$Plot_ID[agb$Plot_ID == "Wells"] <- "WELLS"
agb$Plot_ID[agb$Plot_ID == "BF1"] <- "BP54#1"  # given by Alina
agb$Plot_ID[agb$Plot_ID == "BF2"] <- "BP54#2" # given by Alina
agb$Plot_ID <- str_replace(agb$Plot_ID, "#", "")
agb$Plot_ID <- str_replace(agb$Plot_ID, "CP", "IP")

plots <- unique(agb$Plot_ID)
```


Output to CSV
```{r}
write.csv(agb, file = output_path, eol = "\r\n", row.names = FALSE)

# output plot list
# write.csv(plots, file = plots_path, eol = "\r\n", row.names = FALSE)
```



