agb <- read_csv("plots/agb_plots.csv")
cwd <- read_csv("plots/cwd_plots.csv")
sap <- read_csv("plots/saplings_plots.csv")
soils <- read_csv("plots/soils_plots.csv")
plots <- append(agb$x, cwd$x)
plots <- append(plots, sap$x)
plots <- append(plots, soils$x)
plot <- unique(plots)
plot <- as_tibble(plot)
plot <- plot %>% rename(Name = value)
plot <- plot %>% arrange(Name)
write_csv(plot, "plots/all_plots.csv")

